<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-12-09T23:26:49 IST" name="Test suite dummy" finished-at="2024-12-09T23:27:14 IST" duration-ms="25135">
    <groups>
    </groups>
    <test started-at="2024-12-09T23:26:49 IST" name="AccountCreation" finished-at="2024-12-09T23:27:02 IST" duration-ms="13658">
      <class name="framework.testCases.TCCreateAccount01">
        <test-method is-config="true" signature="initlizeDriver()[pri:0, instance:framework.testCases.TCCreateAccount01@54422e18]" started-at="2024-12-09T23:26:49 IST" name="initlizeDriver" finished-at="2024-12-09T23:26:51 IST" duration-ms="2734" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initlizeDriver -->
        <test-method signature="CreateAccount(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:framework.testCases.TCCreateAccount01@54422e18]" started-at="2024-12-09T23:26:53 IST" name="CreateAccount" data-provider="CreateAccount" finished-at="2024-12-09T23:27:02 IST" duration-ms="9379" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[My]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Name]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[ak1217@gmail.com]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Heoo12334]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[Heoo12334]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1067)
at org.testng.Assert.assertEquals(Assert.java:1031)
at org.testng.Assert.assertEquals(Assert.java:1077)
at framework.testCases.TCCreateAccount01.CreateAccount(TCCreateAccount01.java:31)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreateAccount -->
        <test-method is-config="true" signature="done()[pri:0, instance:framework.testCases.TCCreateAccount01@54422e18]" started-at="2024-12-09T23:27:02 IST" name="done" finished-at="2024-12-09T23:27:02 IST" duration-ms="244" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- done -->
      </class> <!-- framework.testCases.TCCreateAccount01 -->
    </test> <!-- AccountCreation -->
    <test started-at="2024-12-09T23:27:02 IST" name="loginWithCorrectData" finished-at="2024-12-09T23:27:14 IST" duration-ms="11407">
      <class name="framework.testCases.TCSignInWithValid02">
        <test-method is-config="true" signature="initlizeDriver()[pri:0, instance:framework.testCases.TCSignInWithValid02@cecf639]" started-at="2024-12-09T23:27:02 IST" name="initlizeDriver" finished-at="2024-12-09T23:27:04 IST" duration-ms="1605" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initlizeDriver -->
        <test-method signature="signInWithCorrect(java.lang.String,java.lang.String)[pri:0, instance:framework.testCases.TCSignInWithValid02@cecf639]" started-at="2024-12-09T23:27:04 IST" name="signInWithCorrect" data-provider="LoginWithCorrect" finished-at="2024-12-09T23:27:13 IST" duration-ms="9551" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[ak1217@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Heoo12334]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signInWithCorrect -->
        <test-method is-config="true" signature="done()[pri:0, instance:framework.testCases.TCSignInWithValid02@cecf639]" started-at="2024-12-09T23:27:13 IST" name="done" finished-at="2024-12-09T23:27:14 IST" duration-ms="197" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- done -->
      </class> <!-- framework.testCases.TCSignInWithValid02 -->
    </test> <!-- loginWithCorrectData -->
  </suite> <!-- Test suite dummy -->
</testng-results>
